### ISSUE TITLE
Real Time pipeline crashing at the end of the lightcurve stage

### ISSUE THREAD

**Issue by ebachelet** [pyDANDIA/pyDANDIA#134]
Some real time pipeline are crashing at just the end of the lightcurve stage, just after the Star array index number is logged. Here are a list of some real time reductions affected:

Gaia21efs_gp
MOA-2021-BLG-335_rp
MOA-2021-BLG-335_ip

**Comment by rachel3834** [comment]
This seems to be related to new data being added to reductions that are in progress.  It occurs because the HDF5 photometry datafile contains data for a different number of images than the metadata.images_header table where some of the information to build the lightcurve comes from.  

This issue was supposed to be stopped by recent upgrades to the data handling which doesn't transfer data into locked directories.  But that process seems to have believed that the directory was unlocked at the time when the new image was added.  

I have added a catch to stage6 to the effect that if the pipeline is in auto (where the HDF5 is always re-created) then it should be scaled to the number of new_images detected (which handles new data not yet processed by the earlier stages), rather than the total number of images (which includes all frames in the data/ sub-directory).  Since the HDF5 file is re-created on auto, the new_image list should always include all images that have been processed to date. 

This is non-optimal and really needs a more substantial overhaul.
