### ISSUE TITLE
star_catalog.fits information query

### ISSUE THREAD

**Issue by ytsapras** [pyDANDIA/pyDANDIA#18]
For each identified star, we need to agree on what information we want to store in the photometry database (phot_db).

The **stars** table in phot_db is going to be populated from the list of stars identified on a reference image. At the moment this is just a fits table called: **star_catalog.fits**

The columns in this table are:
['Index', 'X_pixel', 'Y_pixel', 'RA_J2000_deg', 'Dec_J2000_deg', 'Instr_mag', 'Instr_mag_err', 'J_mag', 'J_mag_err', 'H_mag', 'H_mag_err', 'Ks_mag', 'Ks_mag_err', 'psf_star']

In phot_db, the  **stars** table is currently defined as:
```
class Stars(TableDef):
    """The object list.
    """
    c_000_star_id = 'INTEGER PRIMARY KEY'
    c_010_ra = 'DOUBLE PRECISION'
    c_020_dec = 'DOUBLE PRECISION'
    c_030_x_pix = 'REAL'
    c_040_y_pix = 'REAL'
    c_050_reference_image = 'INTEGER REFERENCES reference_images(refimg_id)'
    c_060_reference_flux = 'DOUBLE PRECISION'
    c_070_reference_flux_err= 'DOUBLE PRECISION'
    c_100_type = 'TEXT'

    pc_000_raindex = (
        'CREATE INDEX IF NOT EXISTS stars_ra ON stars (ra)')
    pc_010_decindex = (
        'CREATE INDEX IF NOT EXISTS stars_dec ON stars (dec)')
```

**A few questions for all:**

1. Should we use the same column names for the star_catalog.fits table and the **stars** phot_db table? I think we should.
2. Should there be extra or fewer columns in the  **stars** phot_db table? If so, which, and how are they defined? For our project we could use i_mag, r_mag. g_mag for example, but that is not generic enough and we might need an automatic procedure to make this decision for us depending on the data set. We also have measurements from multiple sites for each of these bands so we need to decide on which reference we want stored. 
3. Do we want to store reference fluxes or reference magnitudes?

**Comment by ebachelet** [comment]
I add to this that I gonna need to have ref_flux and error_ref_flux for every star on this table to properly propagate to stage6 photometry.

**Comment by rachel3834** [comment]
There could be an argument for renaming Instr_mag, Instr_mag_err to ref_mag and ref_mag_error, and I can add ref_flux and ref_flux_err, which should be stored in the DB. 

To give my feelings on Yiannis' questions:
1) I think the star_catalog headings should match those in the DB Table. 

2) As I understand it, the purpose of this Table is to record all stars detected in the reference images from ROME, so the fluxes to be stored need to match those produced by ROME (g, r, i) plus the magnitudes from catalog matches.  I don't think we should go an add new columns for fluxes the survey doesn't produce or all possible catalogs - instead, let's decide what we're going to use.  
So that gives us {ref_flux_g, ref_flux_r, ref_flux_i} and {ref_flux_err_g, ref_flux_err_r, ref_flux_err_i} plus currently the 2MASS columns.  I could see an argument for adding e.g. Gaia, or VVV if there are substantial matches.  

3) I don't have strong feelings about storing reference fluxes or mags.  Since these are only stored from the reference images rather than all of them, we could simply store both for convenience.
