### ISSUE TITLE
Stage6 not producing good photometry

### ISSUE THREAD

**Issue by ebachelet** [pyDANDIA/pyDANDIA#44]
I pushed the last version of stage6 and photometry.py to Stage6DB branch. The photometry is still not correct when a delta_flux is found. After several days of search, I can not found why, so I push  here and ask expert to review the function : 

run_psf_photometry_on_difference_image

in the photometry file.

**Comment by mpgh** [comment]
I will try the following: use our quickly calculate difference images, insert them and the s3 target coordinate in the old pipeline and see how the resulting light curve looks. Perhaps that gives us a clue what goes wrong. If it looks like your light curve, we need to look at the subtraction and PSF stages, if it looks fine, the PSF model needs to be revised and we can more directly work on s6.

**Comment by danlegend5** [comment]
May I suggest another approach aswell.

Generate a fake (difference) image with known PSF, known kernel, and no noise. Then fit for the photometry and see what you get back. This should tell you if you have a serious bug in there, and it may give you hints as to what it is if you print out things like the PSF that is being used at intermediate steps. You should get pretty much what you put in (minus slight deviations due to resampling etc in some of the steps). This is how I validated various steps in DanDIA.

I am writing a paper for the Gaia release on 25th April - I can dedicate some time to this sort of issue after the Gaia release. Before that is impossible because the paper has to be ready for the day Gaia DR2 comes out.

**Comment by ebachelet** [comment]
Thanks Dan for the nice idea. I will have a look on it asap. Btw, note that we do not use, yet?, an empirical PSF but an analytical one, i.e Moffat, inside pyDANDIA.
