### ISSUE TITLE
Stage0 produces empty bpms

### ISSUE THREAD

**Issue by mpgh** [pyDANDIA/pyDANDIA#46]
stage0 produces empty bpms and each bpm is stored as a full image which produces to much overhead for Sinistro or other larger format cameras.

**Comment by danlegend5** [comment]
Recommend storing bpms with as small/simple number type as possible (i.e. avoid floats, or long integers. Ideally use a single byte at each pixel - not sure how to do this in python though).

**Comment by ebachelet** [comment]
In principle, stage0 construct one "mastermask" containing all infos needed. For example, one pixel can be mask due to badpixel, but also variable, cosmic ray.... This is managed by 
pixelmasks.py

This is based on multi bollean masking, something similar to
http://blog.millermedeiros.com/using-integers-to-store-multiple-boolean-values/

**Comment by mpgh** [comment]
That sounds like the originally planned structure, currently line 114 writes a full images, but I suspect that comes from the issue of having the bpm in a different extension than in the test dataset.

**Comment by mpgh** [comment]
by commenting out:
save_the_pixel_mask_in_image(reduction_metadata, new_image, master_mask)
the stage still runs without copying data.
