### ISSUE TITLE
stage2 metadata requirements

### ISSUE THREAD

**Issue by mpgh** [pyDANDIA/pyDANDIA#8]
In order to achieve an image ranking, stage2 needs the following information available from the metadata fits:

based on header info (header_summary attribute?)

- MOONFRAC,
- MOONDIST, 
- EXPTIME,
- FILTER and INSTRUMEN ?
- PIXEL SCALE

based on config info (also in metadata which is not implemented yet)

- gain, 
- readout noise, 
- electrons for mag=0 (or rough estimate, might default to 1e9), 
- target magnitude (might default to 17)

based on stage1 output (data_inventory attribute)

- FWHM, 
- ELLIPTICITY, 
- SKY

**Comment by ebachelet** [comment]
Filter are present in header_summary
Instrument should be in reduction_parameters, why you need this?
Pixel scale, gain, ron, emag0, is or should be in reduction_parameters. why you need target magnitude?

Moonfrac and Moondist will be in headers summary if these keyword are present in inst_config file. A task for @ytsapras .

Btw, what happen if you do not have these values because they are simply not existing in the headers? Should stage0 report None values?

**Comment by mpgh** [comment]
MOONFRAC and MOONDIST are not strictly required. If they are not provided, stage2 considers all images. If they are present, stage 2 will exclude "bright time" as defined.

**Comment by ytsapras** [comment]
The MOONFRAC and MOONDIST keywords have now been added to the instrument config files.
You can get the filter and exposure time information from the metadata HEADERS_SUMMARY layer from the columns FILTKEY and EXPKEY respectively.

The rest you can get from the REDUCTION_PARAMETERS layer: columns GAIN, INSTRID, FOV, PIX_SCALE, RON

**Comment by ytsapras** [comment]
The codes should not break if they doesn't find all the parameters. Not all header files will provide the moon distance and fraction.

**Comment by mpgh** [comment]
working version implemented.
